---
title: " "
pagetitle: "Muntasir Masum"
---

<link rel="stylesheet" href="styles.css" type="text/css"> <link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

### [IAPHS Member of the Month](https://iaphs.org/member-of-the-month-muntasir-masum/)

>We spent the year 2020 trying to avoid getting affected by COVID-19 or not act as a carrier. Some of us have been lucky, but many were not. We are only starting to get reliable data on the impacts of COVID-19. But, in my opinion, the long-term health implications of COVID-19 are yet to unfold. The consequences will not just be physiological, rather psychological as well. Cardiovascular, respiratory, neurological, and psychiatric complications will be a few of the long-term health impacts of COVID-19, in addition to numerous others. As a mortality researcher, I would be looking closely into long-term comorbidities due to COVID-19.

______________________________________________________________________________________________________________________

### [Why I joined IAPHS?](https://iaphs.org/embracing-iaphs-and-interdisciplinary-research-a-graduate-students-journey/)

>External travel scholarships for conferences are not easy to come by, and IAPHS offers them to students. That is just one of many reasons to get involved with IAPHS.
    
______________________________________________________________________________________________________________________

### [Brief Overview of Regression Discontinuity Design](https://rpubs.com/muntasir_masum/rdd)
